project:
  type: website
  output-dir: docs

website:
  title: "Data Science Toolkit"
  description: "Comprehensive guides and tools for data science"
  navbar:
    left:
      - href: statistical_modeling/coverpage.qmd
        text: Statistical Modeling
      - href: programming/coverpage.qmd
        text: Programming
      - href: commandline/coverpage.qmd
        text: Command Line
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://jakejing.github.io/datasciencetoolkit/
  sidebar:
    style: "floating"
    search: true

format:
  html:
    theme: cosmo
    css:
      - css/webstyles.css
      - css/blogstyles.css
      - css/shadenote.css
    toc: true
    code-copy: true
    code-fold: false
    # page-layout: full # or "custom" for wider than default
    max-width: 1200px  # specify exact width in pixels
